#!/usr/bin/env bash
#===- run_gemm_bench.sh - GEMM, local and across a link ------------------===#
#
# Part of the Vx Project, under the BSD 3-Clause License.
# See LICENSE for license information.
# SPDX-License-Identifier: BSD-3-Clause
#
#===----------------------------------------------------------------------===#
#
# Times a square GEMM along three paths on a two-GPU box (#348):
#
#   gpu0     dispatched to GPU 0 by the plugin
#   gpu1     dispatched to GPU 1 by the plugin      -- the two should agree
#   remote   dispatched to a worker serving GPU 1   -- the wire, under load
#
# The llama measurement moves small operands very often, so it is dominated by
# round trips. This one moves large ones, so it is dominated by bandwidth, and
# the two together say where the remote path actually costs something.
#
# Per-GEMM cost comes from the slope, as elsewhere: each size is compiled twice
# with different iteration counts, and the difference divided by the difference
# in iterations removes compilation, JIT, the host-side fill loop and process
# startup in one step. Neither absolute time means anything on its own -- at
# these sizes the fill loop alone outweighs the GEMMs.
#
# What is being measured is Vx's GEMM path, not the A100. Operands are staged
# per dispatch and the result staged back (#321), so each iteration carries
# 3*N*N*4 bytes across PCIe around one cuBLAS call. The derived GFLOP/s is
# therefore a property of the current dispatch design; the distance between it
# and the device's peak is the thing worth reading.
#
# Usage, from the bundle directory on the pod after ./setup_gpu_pod.sh:
#   ./run_gemm_bench.sh [-s "256 512 1024 2048"] [-o outdir]
#
#===----------------------------------------------------------------------===#

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# The template lives beside its runner, so finding it needs no path convention at
# all. It used to sit in a shared scripts/templates/ that only one script ever
# substituted -- a coupling nothing expressed, and all nine templates there had
# rotted unnoticed.
TEMPLATE="$SCRIPT_DIR/gpu_gemm_bench.vx"
# The root is the nearest ancestor holding stdlib/: the bundle root on a pod, the
# repo root in a checkout. Taking the script's own directory as the root made this
# runnable only on a pod, which is why nobody saw the template rot.
BUNDLE_DIR="$SCRIPT_DIR"
for _ in 1 2 3 4; do
  [ -d "$BUNDLE_DIR/stdlib" ] && break
  BUNDLE_DIR="$(cd "$BUNDLE_DIR/.." && pwd)"
done
# The compiler: the bundle root on a pod, a cargo target/ directory in a checkout.
if [ -n "${VXC:-}" ]; then
  :
elif [ -x "$BUNDLE_DIR/vxc" ]; then
  VXC="$BUNDLE_DIR/vxc"
elif [ -x "$BUNDLE_DIR/target/release/vxc" ]; then
  VXC="$BUNDLE_DIR/target/release/vxc"
elif [ -x "$BUNDLE_DIR/target/debug/vxc" ]; then
  VXC="$BUNDLE_DIR/target/debug/vxc"
elif command -v vxc >/dev/null 2>&1; then
  VXC="$(command -v vxc)"
else
  echo "error: no vxc found (set VXC=/path/to/vxc)" >&2
  exit 1
fi
SIZES="256 512 1024 2048"
ITERS_LO=20
ITERS_HI=120
OUTDIR="$BUNDLE_DIR/gemm-evidence"

while [ $# -gt 0 ]; do
  case "$1" in
    -s|--sizes) SIZES="$2"; shift 2 ;;
    -o|--out)   OUTDIR="$2"; shift 2 ;;
    --lo)       ITERS_LO="$2"; shift 2 ;;
    --hi)       ITERS_HI="$2"; shift 2 ;;
    -h|--help)  sed -n '10,34p' "${BASH_SOURCE[0]}"; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

cd "$BUNDLE_DIR"
# shellcheck disable=SC1091
[ -f env.sh ] && source env.sh
mkdir -p "$OUTDIR/gen"

if [ ! -f "$TEMPLATE" ]; then
  echo "error: no $TEMPLATE in the bundle" >&2
  exit 1
fi

nvidia-smi --query-gpu=index,name,memory.used --format=csv > "$OUTDIR/hardware.txt" 2>&1

CSV="$OUTDIR/timings.csv"
echo "path,n,iters,seconds" > "$CSV"

# One compile-and-run at a given size, iteration count and device.
run_one() {  # path n iters dev extra_env...
  local path="$1" n="$2" iters="$3" dev="$4"; shift 4
  local src="$OUTDIR/gen/gemm_${n}_${iters}_${dev}.vx"
  sed -e "s/__VX_BENCH_N__/$n/g" \
      -e "s/__VX_BENCH_ITERS__/$iters/g" \
      -e "s/__VX_BENCH_DEV__/$dev/g" \
      -e "s/__VX_BENCH_NOTE__/Generated by run_gemm_bench.sh: N=$n, $iters iterations, GPU $dev./" \
      "$TEMPLATE" > "$src"
  local t0 t1 secs
  t0=$(date +%s.%N)
  env "$@" "$VXC" "$src" --run > "$OUTDIR/out-$path-$n-$iters.txt" 2>&1
  local status=$?
  t1=$(date +%s.%N)
  secs=$(awk -v a="$t0" -v b="$t1" 'BEGIN{printf "%.3f", b-a}')
  if [ $status -ne 0 ]; then
    echo "    $path N=$n iters=$iters FAILED (status $status)" >&2
    tail -3 "$OUTDIR/out-$path-$n-$iters.txt" >&2
    return 1
  fi
  echo "$path,$n,$iters,$secs" >> "$CSV"
  printf '    %-7s N=%-5s iters=%-4s %8ss\n' "$path" "$n" "$iters" "$secs"
}

# --- the two local paths ----------------------------------------------------
for spec in "gpu0 0" "gpu1 1"; do
  set -- $spec
  path="$1"; dev="$2"
  echo "==> $path (plugin, device $dev)"
  for n in $SIZES; do
    run_one "$path" "$n" "$ITERS_LO" "$dev"
    run_one "$path" "$n" "$ITERS_HI" "$dev"
  done
done

# --- the same GEMM, reached over the wire -----------------------------------
#
# The worker serves topology 501 so this row differs from `gpu1` in path alone:
# same device, same arithmetic, and the difference is the marshalling.
echo "==> remote (worker on loopback, device 1)"
cat > "$OUTDIR/loopback.manifest" <<EOF
# Only GPU[1] is listed. GPU[0] is absent, and absent means local -- so a
# program using both would split itself between this process and the worker
# with no further instruction. Here everything is on GPU[1], so everything goes.
GPU[1]  127.0.0.1  19511
EOF

VX_DISPATCH_VERBOSE=1 setsid ./vx-worker --port 19511 --topology 501 --worker-id 1 \
  > "$OUTDIR/worker.log" 2>&1 < /dev/null &
W=$!
sleep 2

if (exec 3<>/dev/tcp/127.0.0.1/19511) 2>/dev/null; then
  for n in $SIZES; do
    run_one remote "$n" "$ITERS_LO" 1 "VX_FLEET_MANIFEST=$OUTDIR/loopback.manifest"
    run_one remote "$n" "$ITERS_HI" 1 "VX_FLEET_MANIFEST=$OUTDIR/loopback.manifest"
  done
  served=$(grep -c 'DISPATCH' "$OUTDIR/worker.log" 2>/dev/null || echo 0)
  echo "  worker served $served dispatches"
  if [ "$served" -eq 0 ]; then
    echo "  FAILURE: the worker served nothing, so the remote row is a local row" >&2
    echo "           under another name and its timings mean nothing." >&2
  fi
else
  echo "  worker never came up; see $OUTDIR/worker.log" >&2
fi

kill "$W" 2>/dev/null
pkill -x vx-worker 2>/dev/null
wait "$W" 2>/dev/null

# --- the numbers ------------------------------------------------------------
echo
# Refuse to present a table when nothing was measured. Every run used to be able to
# fail -- the template had rotted and would not parse -- and this still printed a
# grid of `?`, a DISAGREE, and exited 0, so a caller checking the status learned
# that a sweep measuring nothing had succeeded.
if [ "$(grep -c . "$CSV")" -le 1 ]; then
  echo "error: no measurements recorded; every run failed. See $OUTDIR/out-*.txt" >&2
  exit 1
fi

echo "=== Per-GEMM cost, and what it implies ==="
awk -F, -v lo="$ITERS_LO" -v hi="$ITERS_HI" '
  NR>1 { t[$1,$2,$3] = $4; paths[$1]=1; sizes[$2]=1 }
  END {
    printf "  %-7s %6s %12s %12s %14s\n", "path", "N", "ms/GEMM", "GFLOP/s", "staged MB/GEMM"
    np = split("gpu0 gpu1 remote", order, " ")
    ns = 0; for (s in sizes) sz[++ns] = s+0
    for (i=1; i<ns; i++) for (j=i+1; j<=ns; j++) if (sz[i] > sz[j]) { x=sz[i]; sz[i]=sz[j]; sz[j]=x }
    for (p=1; p<=np; p++) {
      pa = order[p]
      if (!(pa in paths)) continue
      for (i=1; i<=ns; i++) {
        n = sz[i]
        if (!((pa,n,lo) in t) || !((pa,n,hi) in t)) continue
        per = (t[pa,n,hi] - t[pa,n,lo]) / (hi - lo)
        # 2*N^3 flops per GEMM; 3 N*N f32 buffers cross per dispatch.
        gflops = (per > 0) ? (2.0*n*n*n) / (per*1e9) : 0
        mb = 3.0*n*n*4 / 1048576
        printf "  %-7s %6d %12.3f %12.1f %14.1f\n", pa, n, per*1000, gflops, mb
        cost[pa,n] = per
      }
    }
    print ""
    for (i=1; i<=ns; i++) {
      n = sz[i]
      if ((("gpu1",n) in cost) && (("remote",n) in cost) && cost["gpu1",n] > 0) {
        d = cost["remote",n] - cost["gpu1",n]
        printf "  N=%-5d the wire adds %8.3f ms/GEMM (%.1fx) over the same device locally\n", \
               n, d*1000, cost["remote",n]/cost["gpu1",n]
      }
    }
  }' "$CSV"

echo
echo "=== Did the two devices agree? ==="
for n in $SIZES; do
  f0="$OUTDIR/out-gpu0-$n-$ITERS_LO.txt"
  f1="$OUTDIR/out-gpu1-$n-$ITERS_LO.txt"
  fr="$OUTDIR/out-remote-$n-$ITERS_LO.txt"
  v0=$(grep -oE '^[0-9.]+ [0-9]+$' "$f0" 2>/dev/null | head -1)
  v1=$(grep -oE '^[0-9.]+ [0-9]+$' "$f1" 2>/dev/null | head -1)
  vr=$(grep -oE '^[0-9.]+ [0-9]+$' "$fr" 2>/dev/null | head -1)
  printf '  N=%-5s gpu0=%-22s gpu1=%-22s remote=%-22s' "$n" "${v0:-?}" "${v1:-?}" "${vr:-?}"
  if [ -n "$v0" ] && [ "$v0" = "$v1" ] && { [ -z "$vr" ] || [ "$v0" = "$vr" ]; }; then
    echo "  agree"
  else
    echo "  DISAGREE"
    DISAGREED=1
  fi
done

echo
echo "Evidence in $OUTDIR/ (timings.csv is the raw data)"

# A disagreement between two devices computing the same GEMM is the finding this
# script exists to surface, so it is a failure rather than a remark.
if [ "${DISAGREED:-0}" = "1" ]; then
  echo "error: the devices did not agree; the numbers above describe different results" >&2
  exit 1
fi
