#===- config.toml - Vx Compiler ---------------------------------*- TOML -*-===#
#
# Part of the Vx Project, under the Apache License v2.0 with LLVM Exceptions.
# See LICENSE for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
#===----------------------------------------------------------------------===#
[alias]
vx-bench = "run --release --bin cargo-vx-bench --"
