#!/usr/bin/env bash
#===- measure_wire_traffic.sh - what a dispatch costs on the wire --------===#
#
# Part of the Vx Project, under the BSD 3-Clause License.
# See LICENSE for license information.
# SPDX-License-Identifier: BSD-3-Clause
#
#===----------------------------------------------------------------------===#
#
# Counts the messages a program sends to a worker, per dispatch (#348).
#
# Round trips are the fleet's unit of cost. Each one is a full network latency,
# and for a small operand that dwarfs the bytes by orders of magnitude -- so a
# dispatch that takes six round trips is six latencies whatever it computes.
# "About six" was an estimate nobody could check, because the worker logged
# TRANSFER and DISPATCH and not FETCH or FREE. It now counts all four and
# reports them when the host disconnects, and this reads that.
#
# Needs no GPU and no second machine: the worker is built against the CPU
# backend and served over loopback, which is the same code path a real fleet
# takes with a different address and no latency to hide behind.
#
#   ./scripts/measure_wire_traffic.sh [-n iterations] [-o outdir]
#
# What to read: `messages per dispatch`. Bytes matter too, but a program that
# re-sends an unchanged weight every iteration shows up in the *count* first,
# and that is the thing residency is meant to remove.
#
#===----------------------------------------------------------------------===#

set -euo pipefail

ITERS=8
OUTDIR="${TMPDIR:-/tmp}/vx-wire-traffic"
PORT=$((21000 + RANDOM % 2000))

while [ $# -gt 0 ]; do
  case "$1" in
    -n|--iters) ITERS="$2"; shift 2 ;;
    -o|--out)   OUTDIR="$2"; shift 2 ;;
    -p|--port)  PORT="$2"; shift 2 ;;
    -h|--help)  sed -n '9,28p' "${BASH_SOURCE[0]}"; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

mkdir -p "$OUTDIR"
VXC="${VXC:-./target/release/vxc}"
[ -x "$VXC" ] || { echo "error: no $VXC (cargo build --release)" >&2; exit 1; }

CXX="${CXX:-clang++}"
FFI_CFLAGS=$(pkg-config --cflags libffi 2>/dev/null || true)
FFI_LIBS=$(pkg-config --libs libffi 2>/dev/null || echo "-lffi")

echo "==> building a CPU-backed worker"
# shellcheck disable=SC2086
$CXX -std=c++17 -O1 -Wall \
  runtime/vx_worker_main.cpp runtime/host_dispatch.cpp \
  $FFI_CFLAGS $FFI_LIBS \
  -o "$OUTDIR/vx-worker"

# A matmul in a loop: the shape a fleet actually runs, and the one where
# re-sending an operand that did not change is visible.
#
# Quoted heredoc, with the iteration count substituted afterwards. The body is
# program text, and an unquoted heredoc runs anything in it that looks like
# shell -- a pair of backticks in a comment here was executed, and the comment
# arrived with a hole in it.
cat > "$OUTDIR/prog.vx" <<'EOF'
//===- generated by measure_wire_traffic.sh ---------------------*- Vx -*-===//
// __VX_ITERS__ dispatches over one pair of operands that never change. A run
// that transfers them once has done the right thing; one that transfers them
// every iteration is paying a round trip per operand per dispatch for bytes the
// worker already has.
fn main() -> i32 {
  let mut a = Tensor<f32>([ 64, 64 ]);
  let mut b = Tensor<f32>([ 64, 64 ]);
  let mut c = Tensor<f32>([ 64, 64 ]);
  for i in 0..64 {
    for j in 0..64 {
      a[i][j] = ((i + j) as f32) * 0.01;
      b[i][j] = ((i - j) as f32) * 0.02;
    }
  }
  // matmul_into, not "c = a @ b": the second publishes its result into a slot,
  // and a slot is a descriptor naming memory in this process, so a worker
  // cannot fill it and the dispatch declines to route. That decline is correct,
  // and it would make this a measurement of a program that never left the host.
  for step in 0..__VX_ITERS__ {
    spawn on(Topology::GPU) {
      matmul_into(&mut c, &a, &b);
    }
  }
  print(c[0][0]);
  return 0;
}
EOF
sed -i.bak "s/__VX_ITERS__/$ITERS/g" "$OUTDIR/prog.vx" && rm -f "$OUTDIR/prog.vx.bak"

cat > "$OUTDIR/manifest" <<EOF
# One worker, serving the topology the program places on.
GPU[0]  127.0.0.1  $PORT
EOF

echo "==> starting the worker on 127.0.0.1:$PORT"
# `setsid` where it exists (Linux), plain background otherwise (macOS has none).
# Detaching matters on a pod, where a worker sharing the terminal's process
# group is killed by the same Ctrl-C that stops the harness mid-measurement.
SETSID=$(command -v setsid || true)
$SETSID "$OUTDIR/vx-worker" --port "$PORT" --topology 0 --worker-id 2 \
  > "$OUTDIR/worker.log" 2>&1 < /dev/null &
W=$!
sleep 1

if ! (exec 3<>/dev/tcp/127.0.0.1/"$PORT") 2>/dev/null; then
  echo "error: the worker never came up; see $OUTDIR/worker.log" >&2
  cat "$OUTDIR/worker.log" >&2
  kill "$W" 2>/dev/null || true
  exit 1
fi

echo "==> running $ITERS dispatches"
# VX_FLEET_STRICT: if a placement is not in the manifest it runs here, and the
# whole measurement would then be of a program that never touched the wire.
VX_FLEET_STRICT=1 VX_FLEET_MANIFEST="$OUTDIR/manifest" \
  "$VXC" "$OUTDIR/prog.vx" --run > "$OUTDIR/run.out" 2> "$OUTDIR/run.err" || {
    echo "error: the program failed" >&2
    tail -20 "$OUTDIR/run.err" >&2
    kill "$W" 2>/dev/null || true
    exit 1
  }

# The worker reports its totals when the host disconnects, so it has to be
# given a moment to notice and then stopped.
sleep 1
kill "$W" 2>/dev/null || true
wait "$W" 2>/dev/null || true

echo
echo "=== what the worker served ==="
SUMMARY=$(grep 'served .* message' "$OUTDIR/worker.log" | tail -1 || true)
if [ -z "$SUMMARY" ]; then
  echo "  the worker served nothing -- the run never reached it." >&2
  echo "  $OUTDIR/worker.log:" >&2
  tail -20 "$OUTDIR/worker.log" >&2
  exit 1
fi
echo "  $SUMMARY"

python3 - "$SUMMARY" "$ITERS" <<'PY'
import re, sys
summary, iters = sys.argv[1], int(sys.argv[2])
counts = {k: (int(n), int(b))
          for k, n, b in re.findall(r'(\w+)=(\d+) \((\d+) B\)', summary)}
total = sum(n for n, _ in counts.values())
dispatches = counts.get("DISPATCH", (0, 0))[0]
print()
print(f"  {'kind':<10} {'messages':>9} {'per dispatch':>13} {'bytes':>12}")
for kind in ("TRANSFER", "DISPATCH", "FETCH", "FREE"):
    n, b = counts.get(kind, (0, 0))
    per = f"{n / dispatches:.2f}" if dispatches else "-"
    print(f"  {kind:<10} {n:>9} {per:>13} {b:>12}")
print(f"  {'total':<10} {total:>9} "
      f"{(total / dispatches if dispatches else 0):>13.2f}")
print()
if dispatches != iters:
    print(f"  WARNING: {iters} iterations in the program, {dispatches} "
          f"dispatches on the wire.")
    print("  The two should agree; if they do not, some iterations ran here.")
PY

echo "Evidence in $OUTDIR/ (worker.log is the raw count)"
