#!/usr/bin/env bash
#===- run_flash_bench.sh - what a placed non-matmul kernel actually costs -===#
#
# Part of the Vx Project, under the BSD 3-Clause License.
# See LICENSE for license information.
# SPDX-License-Identifier: BSD-3-Clause
#
#===----------------------------------------------------------------------===#
#
# Times the fused flash-attention forward from flash_attention_bench.vx across
# sequence lengths, and says plainly where it ran (#348, #251).
#
# The headline is not the time. It is that `spawn on(Topology::GPU)` places this
# kernel, transfers Q/K/V/O into GPU_HBM, and then runs the arithmetic on the
# host, because only `kind=matmul` routes to cuBLAS and a fused online-softmax
# loop nest is not a GEMM. The script asserts that rather than assuming it: it
# greps the trace for the refusal, and it counts GEMM dispatches, which must be
# zero. A future kernel-emission path (#251) would change both, and the same
# script would then be measuring a GPU.
#
# Cost per unit of work comes from the slope. Only the sequence length K varies,
# so the work scales linearly in it while the output tensor -- and therefore the
# printing, the compilation and the process startup -- stays fixed and lands in
# the intercept.
#
# Usage, from the bundle directory on the pod:
#   ./run_flash_bench.sh [-q rows] [-d head_dim] [-k "512 1024 2048 4096"]
#
#===----------------------------------------------------------------------===#

set -uo pipefail

BUNDLE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# The bundle root is whichever directory holds stdlib/ -- the script's own on a pod,
# where it is copied to the bundle root, and its parent in a checkout, where the
# script lives in scripts/. Assuming the script's own directory was the root made
# this runnable only on a pod: from the repo it looked for the template under
# scripts/scripts/, then for "$VXC", then failed to resolve std::math. Nobody could
# run it from a checkout to notice the template had rotted.
if [ ! -d "$BUNDLE_DIR/stdlib" ] && [ -d "$BUNDLE_DIR/../stdlib" ]; then
  BUNDLE_DIR="$(cd "$BUNDLE_DIR/.." && pwd)"
fi
# The compiler: the bundle root on a pod, a cargo target/ directory in a checkout.
if [ -n "${VXC:-}" ]; then
  :
elif [ -x "$BUNDLE_DIR/vxc" ]; then
  VXC="$BUNDLE_DIR/vxc"
elif [ -x "$BUNDLE_DIR/target/release/vxc" ]; then
  VXC="$BUNDLE_DIR/target/release/vxc"
elif [ -x "$BUNDLE_DIR/target/debug/vxc" ]; then
  VXC="$BUNDLE_DIR/target/debug/vxc"
elif command -v vxc >/dev/null 2>&1; then
  VXC="$(command -v vxc)"
else
  echo "error: no vxc found (set VXC=/path/to/vxc)" >&2
  exit 1
fi
TEMPLATE="scripts/templates/flash_attention_bench.vx"
SQ=128
HD=64
TILE=64
KS="512 1024 2048 4096"
REPS=2
OUTDIR="$BUNDLE_DIR/flash-evidence"

while [ $# -gt 0 ]; do
  case "$1" in
    -q) SQ="$2"; shift 2 ;;
    -d) HD="$2"; shift 2 ;;
    -k) KS="$2"; shift 2 ;;
    -t) TILE="$2"; shift 2 ;;
    -n) REPS="$2"; shift 2 ;;
    -o) OUTDIR="$2"; shift 2 ;;
    -h|--help) sed -n '10,27p' "${BASH_SOURCE[0]}"; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

cd "$BUNDLE_DIR"
# shellcheck disable=SC1091
[ -f env.sh ] && source env.sh
mkdir -p "$OUTDIR/gen"

[ -f "$TEMPLATE" ] || { echo "error: no $TEMPLATE in the bundle" >&2; exit 1; }

nvidia-smi --query-gpu=index,name,memory.used --format=csv > "$OUTDIR/hardware.txt" 2>&1
CSV="$OUTDIR/timings.csv"
echo "sq,sk,hd,rep,seconds" > "$CSV"

emit() {  # sk -> path
  # Two statements, not one. Bash expands every word of a `local` command
  # before performing any of its assignments, so `${sk}` on the same line is
  # still unset -- and under `set -u` that aborts the function, which left the
  # probe compiling an empty path and the trace reporting neither a refusal nor
  # a dispatch.
  local sk="$1"
  local src="$OUTDIR/gen/flash_${SQ}_${sk}_${HD}.vx"
  sed -e "s/__VX_SQ__/$SQ/g" -e "s/__VX_SK__/$sk/g" -e "s/__VX_HD__/$HD/g" \
      -e "s/__VX_TILE__/$TILE/g" -e "s#__VX_NT__#$(( sk / TILE ))#g" \
      -e "s/__VX_BENCH_NOTE__/Generated by run_flash_bench.sh: ${SQ}x${sk}, head ${HD}, tile ${TILE}./" \
      "$TEMPLATE" > "$src"
  echo "$src"
}

# --- where does it run? ------------------------------------------------------
#
# Asked once, at the smallest size, with narration on. Everything below is a
# CPU measurement if this says the kernel was not routed -- and a GPU one if a
# later kernel-emission path makes it say otherwise. Either way the script
# should report which, rather than the reader assuming.
probe=$(emit "$(echo "$KS" | awk '{print $1}')")
VX_DISPATCH_VERBOSE=1 "$VXC" "$probe" --run > "$OUTDIR/probe.txt" 2>&1
# Whether the probe RAN is a different question from what it printed, and the counts below cannot
# tell them apart: a program that failed to compile produces exactly the same silent trace as one
# that ran and narrated nothing. That cost real time -- a bundle without `stdlib/` reachable dies
# with "Could not resolve import 'std::math'", and the script reported it as "the trace is not
# saying what happened", which sent the search toward CUDA instead of the import path.
if ! grep -qE '^\[JIT\] Executing native binary' "$OUTDIR/probe.txt"; then
  echo "error: the probe never ran. First lines of $OUTDIR/probe.txt:" >&2
  head -5 "$OUTDIR/probe.txt" >&2
  exit 1
fi
refused=$(grep -c 'not routed; running on the host' "$OUTDIR/probe.txt")
# A machine with no device at all answers the question just as clearly, and with a different
# message: the runtime says so once, up front, instead of refusing a kernel per dispatch. Without
# this the script cannot establish a CPU baseline anywhere except on a GPU box, which is the one
# place a CPU baseline is not what you went there for.
nodevice=$(grep -c '^\[Vx CUDA\] no CUDA device' "$OUTDIR/probe.txt")
gemms=$(grep -c '^\[Vx CUDA\] GEMM ' "$OUTDIR/probe.txt")
stages=$(grep -c '^\[Vx CUDA\] device . stage' "$OUTDIR/probe.txt")
# The trace's newest sentence: the kernel was not refused and not reclassified
# as a GEMM -- the compiler emitted a device image for it and the runtime
# launched that (#251). This is the outcome the header of this script said did
# not exist yet, so before it existed the verdict below correctly refused to
# name it.
images=$(grep -c 'ran on GPU . from its own image' "$OUTDIR/probe.txt")

echo "=== Where does this kernel run? ==="
echo "  operands staged to the device: $stages"
echo "  GEMM dispatches:               $gemms"
echo "  kernels refused and run on the host: $refused"
echo "  kernels run from their own device image: $images"
if [ "$nodevice" -gt 0 ] && [ "$gemms" -eq 0 ]; then
  echo "  => there is no device on this machine. Every number below is a CPU number,"
  echo "     and it is a CPU baseline rather than evidence about a GPU."
  WHERE=host-nodevice
elif [ "$images" -gt 0 ]; then
  # The launch shape is in the trace -- "(28 params, 1x128 threads)" -- and it is the
  # difference between pricing the emission path and pricing the device, so report it
  # rather than assuming either.
  shape=$(grep -oE '[0-9]+x[0-9]+ threads' "$OUTDIR/probe.txt" | head -1)
  echo "  => the compiler's own kernel ran on the device (#251), as ${shape:-an unreported shape}."
  echo "     A 1x1 launch prices the emission path; a wider one is the frontend's"
  echo "     disjointness proof cashed in as blocks x threads (grid-striding)."
  WHERE=gpu-image
elif [ "$refused" -gt 0 ] && [ "$gemms" -eq 0 ]; then
  echo "  => a device is present and the kernel was refused. Every number below is a CPU number."
  WHERE=host
elif [ "$gemms" -gt 0 ]; then
  echo "  => something routed to cuBLAS; read the trace before believing the rest"
  WHERE=gpu
else
  echo "  => neither refused nor routed. The trace is not saying what happened;" >&2
  echo "     stopping rather than reporting times for an unknown execution." >&2
  exit 1
fi

# --- time it -----------------------------------------------------------------
echo
echo "=== Timing (${SQ} queries, head dim ${HD}, tile ${TILE}) ==="
for sk in $KS; do
  src=$(emit "$sk")
  for rep in $(seq 1 "$REPS"); do
    t0=$(date +%s.%N)
    "$VXC" "$src" --run > "$OUTDIR/out-$sk-$rep.txt" 2>&1
    st=$?
    t1=$(date +%s.%N)
    secs=$(awk -v a="$t0" -v b="$t1" 'BEGIN{printf "%.3f", b-a}')
    if [ $st -ne 0 ]; then
      echo "    K=$sk rep $rep FAILED (status $st)" >&2
      tail -3 "$OUTDIR/out-$sk-$rep.txt" >&2
      continue
    fi
    echo "$SQ,$sk,$HD,$rep,$secs" >> "$CSV"
    printf '    K=%-6s rep %d  %8ss\n' "$sk" "$rep" "$secs"
  done
done

# --- the closed form ---------------------------------------------------------
#
# Row 0 of Q is all zeros, so every score is zero, the softmax is uniform, and
# o[0][d] is the mean of column d of V: 0.01*(K-1)/2. A kernel that ran but
# computed the wrong thing would still produce timings, so this is what says the
# timings are of the intended computation.
echo
echo "=== Did it compute the right thing? ==="
for sk in $KS; do
  f="$OUTDIR/out-$sk-1.txt"
  [ -f "$f" ] || continue
  got=$(grep -oE '^\[\[[0-9.e-]+' "$f" | head -1 | tr -d '[')
  want=$(awk -v k="$sk" 'BEGIN{printf "%.6f", 0.01*(k-1)/2}')
  ok=$(awk -v g="${got:-0}" -v w="$want" 'BEGIN{d=g-w; if(d<0)d=-d; print (w>0 && d/w < 0.001) ? "ok" : "MISMATCH"}')
  printf '  K=%-6s o[0][0] = %-12s expected %-12s %s\n' "$sk" "${got:-<none>}" "$want" "$ok"
done

# --- cost per unit of work ---------------------------------------------------
#
# Attention is 4*SQ*SK*HD flops: two multiply-accumulates per (query, key,
# depth) triple, one for QK^T and one for PV. The slope against SK removes the
# fixed cost, and the achieved rate is what a placed non-matmul kernel is worth
# today -- to be read against the 16.2 TFLOP/s a resident cuBLAS SGEMM reaches
# on this same device (scripts/gemm_anatomy.cu).
echo
echo "=== Cost of the fused kernel (slope against sequence length) ==="
awk -F, -v sq="$SQ" -v hd="$HD" -v where="$WHERE" '
  NR>1 { if (!(($2) in best) || $5 < best[$2]) best[$2] = $5 }
  END {
    n = 0
    for (k in best) { n++; x[n] = k + 0; y[n] = best[k] + 0 }
    if (n < 2) { print "  not enough sizes to fit"; exit }
    for (i = 1; i < n; i++)
      for (j = i + 1; j <= n; j++)
        if (x[i] > x[j]) { t = x[i]; x[i] = x[j]; x[j] = t; t = y[i]; y[i] = y[j]; y[j] = t }
    sx = sy = sxx = sxy = 0
    for (i = 1; i <= n; i++) { sx += x[i]; sy += y[i]; sxx += x[i]*x[i]; sxy += x[i]*y[i] }
    d = n*sxx - sx*sx
    m = (n*sxy - sx*sy) / d
    b = (sy - m*sx) / n
    printf "  fixed cost (compile, JIT, print): %.2f s\n", b
    printf "  per unit of K:                    %.4f ms\n", m*1000
    printf "\n  %-8s %12s %14s\n", "K", "kernel (s)", "GFLOP/s"
    for (i = 1; i <= n; i++) {
      kern = m * x[i]
      gf = 4.0 * sq * x[i] * hd / 1e9
      printf "  %-8d %12.3f %14.2f\n", x[i], kern, (kern > 0 ? gf/kern : 0)
    }
    printf "\n  A resident cuBLAS SGEMM on this device reaches 16223 GFLOP/s.\n"
    if (where == "host")
      printf "  This kernel is not on the device at all, which is the gap #251 closes.\n"
    if (where == "gpu-image")
      printf "  This kernel IS on the device. What remains of the distance to cuBLAS\n  is how much of the device the launch occupies, not placement.\n"
  }' "$CSV"

echo
echo "Evidence in $OUTDIR/"
